server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:demo;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

app:
  jwt:
    secret: ${JWT_SECRET:X9aLp3qR7tVw2mZ8sB4yN6hC0dJ5fK1u}
    expiration-ms: 3600000